name: gallery
description: One Flutter App.

dependencies:
  flutter:
    sdk: flutter
  collection: 1.14.3
  intl: 0.15.1
  string_scanner: 1.0.2
  url_launcher: 0.4.2+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true
  assets:
    - lib/gallery/example_code.dart
    - images/appbar_background.jpg
    - images/appbar/appbar_background_layer0.png
    - images/appbar/appbar_background_layer1.png
    - images/appbar/appbar_background_layer2.png
    - images/appbar/appbar_background_layer3.png
    - images/appbar/appbar_background_layer4.png
    - images/appbar/appbar_background_layer5.png
    - images/pesto/avatar.jpg
    - images/pesto/image10.jpg
    - images/pesto/image11.jpg
    - images/pesto/image12.jpg
    - images/pesto/image13.jpg
    - images/pesto/image1.jpg
    - images/pesto/image2.jpg
    - images/pesto/image3.jpg
    - images/pesto/image4.jpg
    - images/pesto/image5.jpg
    - images/pesto/image6.jpg
    - images/pesto/image7.jpg
    - images/pesto/image8.jpg
    - images/pesto/image9.jpg
    - images/pesto/logo_small.png
    - images/pesto/logo_medium.png
    - images/pesto/fish.png
    - images/pesto/healthy.png
    - images/pesto/main.png
    - images/pesto/meat.png
    - images/pesto/quick.png
    - images/pesto/spicy.png
    - images/pesto/veggie.png
    - images/about_logo.png
    - images/ali_connors.jpg
    - images/drawer_logo.png
    - images/kangaroo_valley_safari.jpg
    - images/top_10_australian_beaches.jpg
    - images/landscape_0.jpg
    - images/landscape_1.jpg
    - images/landscape_2.jpg
    - images/landscape_3.jpg
    - images/landscape_4.jpg
    - images/landscape_5.jpg
    - images/landscape_6.jpg
    - images/landscape_7.jpg
    - images/landscape_8.jpg
    - images/landscape_9.jpg
    - images/landscape_10.jpg
    - images/landscape_11.jpg
    - images/shrine/products/backpack.png
    - images/shrine/products/beachball.png
    - images/shrine/products/binoculars.png
    - images/shrine/products/brush.png
    - images/shrine/products/chair.png
    - images/shrine/products/chucks.png
    - images/shrine/products/clock.png
    - images/shrine/products/fish_bowl.png
    - images/shrine/products/flippers.png
    - images/shrine/products/green-shoes.png
    - images/shrine/products/heels.png
    - images/shrine/products/helmet.png
    - images/shrine/products/lawn_chair.png
    - images/shrine/products/lipstick.png
    - images/shrine/products/popsicle.png
    - images/shrine/products/radio.png
    - images/shrine/products/sunnies.png
    - images/shrine/products/surfboard.png
    - images/shrine/products/teapot.png
    - images/shrine/vendors/16c477b.jpg
    - images/shrine/vendors/ali-connors.png
    - images/shrine/vendors/peter-carlsson.png
    - images/shrine/vendors/sandra-adams.jpg
    - images/shrine/vendors/zach.jpg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
